sfdx force:data:tree:export -u $1 -q "SELECT Name, Label__c,  Status__c FROM Orchestration__c "
sfdx force:data:tree:export -u $1 -q "SELECT Name, Label__c, Type__c, Status__c, Orchestration__c FROM OrchestrationMember__c "
sfdx force:data:tree:export -u $1 -q "SELECT Name, Model__c, Issue__c, Frequency__c, Category__c FROM RepairProcedure__c "
sfdx force:data:tree:export -u $1 -q "SELECT Name, Description__c, Part_Number__c, PreferredVendor__c, RepairProcedure__c FROM RepairPart__c "
sfdx force:data:tree:export -u $1 -q "SELECT Name, AnotherRepairPartLookup__c,RepairProcedure__c FROM RequiredPart__c "
sfdx force:data:tree:export -u $1 -q "SELECT Name, InventoryStatus__c, RepairPart__c FROM InventoryReport__c "
sfdx force:data:tree:export -u $1 -q "SELECT Name, IntegrationType__c FROM PartsVendor__c "
sfdx force:data:tree:export -u $1 -q "SELECT Name FROM Account "
sfdx force:data:tree:export -u $1 -q "SELECT Name, AccountId FROM Contact "